name: SwayLend USDT Market
networks:
  - id: 0
    start_block: 10529800
    contracts:
      - name: Market
        address: 0x31dd8615e8179e532c33247dbae929afffa924a6fd95464628eec37fe9175c6a
        abi_file_path: ./abi/market-abi.json
        handler: ./src/EventHandlers.ts
        events:
          - name: CollateralAssetAdded
          - name: CollateralAssetUpdated
          - name: CollateralAssetPaused
          - name: CollateralAssetResumed
          - name: UserBasicEvent
          - name: MarketBasicEvent
          - name: UserSupplyCollateralEvent
          - name: UserWithdrawCollateralEvent
          - name: UserSupplyBaseEvent
          - name: UserWithdrawBaseEvent
          - name: AbsorbCollateralEvent
          - name: UserLiquidatedEvent
          - name: BuyCollateralEvent
          - name: ReservesWithdrawnEvent
          - name: PauseConfigurationEvent
          - name: MarketConfigurationEvent
