name: Fuel Greeter Indexer
networks:
  - id: 0
    start_block: 9910000
    contracts:
      - name: Market
        address: 0x79d9be371612a8e367db167549797bf4228081cb2147cfe1bab0d369f401c821
        abi_file_path: ./abi/market-abi.json
        handler: ./src/EventHandlers.ts
        events:
          - name: CollateralAssetAdded
          - name: CollateralAssetUpdated
          - name: CollateralAssetPaused
          - name: CollateralAssetResumed
          - name: UserBasicEvent
          - name: MarketBasicEvent
          - name: UserSupplyCollateralEvent
          - name: UserWithdrawCollateralEvent
          - name: UserSupplyBaseEvent
          - name: UserWithdrawBaseEvent
          - name: AbsorbCollateralEvent
          - name: UserLiquidatedEvent
          - name: BuyCollateralEvent
          - name: ReservesWithdrawnEvent
          - name: PauseConfigurationEvent
          - name: MarketConfigurationEvent
