name: Swaylend USDC Mock Market
ecosystem: fuel
networks:
  - id: 0
    start_block: 11380000
    contracts:
      - name: Market
        address: 0x42c1c50d215ab2d50c08160d20c318b7c27ea7e2a8adc9dd7fca1d1428afb70d
        abi_file_path: ./abi/market-abi.json
        handler: ./src/EventHandlers.ts
        events:
          - name: CollateralAssetAdded
          - name: CollateralAssetUpdated
          - name: CollateralAssetPaused
          - name: CollateralAssetResumed
          - name: UserBasicEvent
          - name: MarketBasicEvent
          - name: UserSupplyCollateralEvent
          - name: UserWithdrawCollateralEvent
          - name: UserSupplyBaseEvent
          - name: UserWithdrawBaseEvent
          - name: AbsorbCollateralEvent
          - name: UserLiquidatedEvent
          - name: BuyCollateralEvent
          - name: ReservesWithdrawnEvent
          - name: PauseConfigurationEvent
          - name: MarketConfigurationEvent
